server:
  port: 13000
spring:
  application:
    name: cloud-order
  datasource:
    url: jdbc:mysql://121.40.24.147:3306/cloud_product?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8
    username: root
    password: sunshine

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  typeAliasesPackage: pers.example.product.dao.domain
  configuration:
    map-underscore-to-camel-case: true

dubbo:
  protocol:
    port: 20883
    name: dubbo
  registry:
    address: nacos://121.40.24.147:8848?namespace=8c740e4c-abe8-4336-a519-0dcfbcae3bd1
