aliyun: 121.40.24.147
server:
  port: 12020
spring:
  datasource:
    url: jdbc:mysql://${aliyun}:3306/cloud_gateway?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8
    username: root
    password: sunshine
  application:
    name: gateway
  cloud:
    gateway:
      verbose:
        enable: true
    nacos:
      discovery:
        server-addr: ${aliyun}:8848
        namespace: 8c740e4c-abe8-4336-a519-0dcfbcae3bd1

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  typeAliasesPackage: pers.example.gateway.dao.domain
  configuration:
    map-underscore-to-camel-case: true