server:
  port: 12020
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_gateway?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8
    username: root
    password: sunshine
  application:
    name: gateway
  cloud:
    gateway:
      verbose:
        enable: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 40cc1790-abfa-411a-94bc-59817ed256c4
        group: TEST_GROUP

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  typeAliasesPackage: org.example.gateway.dao.domain
  configuration:
    map-underscore-to-camel-case: true