aliyun: 39.104.70.173
server:
  port: 12020
spring:
  datasource:
    url: jdbc:mysql://${aliyun}:3306/cloud_gateway?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8
    username: root
    password: sunshine
  application:
    name: gateway
  cloud:
    gateway:
      verbose:
        enable: true
    nacos:
      discovery:
        server-addr: 39.104.70.173:8848
        namespace: ed6cf126-56a1-4dc6-b418-6887a55daaf2
#        namespace: ed6cf126-56a1-4dc6-b418-6887a55daaf2

#mybatis:
#  mapper-locations: classpath:/mappers/*Mapper.xml
#  typeAliasesPackage: pers.example.gateway.dao.domain
#  configuration:
#    map-underscore-to-camel-case: true

nacos:
  config:
    server-addr: 39.104.70.173:8848
    namespace: ed6cf126-56a1-4dc6-b418-6887a55daaf2