server:
  port: 10020
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, env, metrics, gateway

spring:
  application:
    name: gateway
  cloud:
    gateway:
      verbose:
        enable: true
#    gateway:
#      routes:
#        - id: prule
#          uri: lb://nacos-provider-1
#          predicates:
#            - Path=/provider/**
#          filters:
#            - StripPrefix=1
#        - id: crule
#          uri: lb://nacos-consumer-1
#          predicates:
#            - Path=/consumer/**

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848